"""
NORTHSTAR MODEL VALIDATION
Calibration Analysis V0.2

Purpose:
    Independently evaluate whether model predicted probabilities
    correspond to observed event rates on the validation sample.

The analysis uses validation predictions already generated by
the Baseline Model V0.1.

Important:
    This script does NOT retrain the model.
    This script does NOT modify baseline outputs.
    This script evaluates probability calibration only.

Input:
    reports/baseline/validation_predictions.csv

Required columns:
    SK_ID_CURR
    y_true
    y_probability
    y_prediction

Outputs:
    reports/calibration/
        calibration_metrics.csv
        calibration_by_decile.csv
        calibration_curve.png
"""


from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.metrics import (
    brier_score_loss,
    log_loss,
)


# ============================================================
# CONFIGURATION
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[1]

PREDICTIONS_PATH = (
    PROJECT_ROOT
    / "reports"
    / "baseline"
    / "validation_predictions.csv"
)

OUTPUT_DIR = (
    PROJECT_ROOT
    / "reports"
    / "calibration"
)

METRICS_PATH = (
    OUTPUT_DIR
    / "calibration_metrics.csv"
)

DECILE_PATH = (
    OUTPUT_DIR
    / "calibration_by_decile.csv"
)

PLOT_PATH = (
    OUTPUT_DIR
    / "calibration_curve.png"
)

ID_COLUMN = "SK_ID_CURR"
TARGET_COLUMN = "y_true"
PROBABILITY_COLUMN = "y_probability"
PREDICTION_COLUMN = "y_prediction"

N_BINS = 10


# ============================================================
# HELPERS
# ============================================================

def print_section(title):
    """Print formatted section header."""

    print()
    print("=" * 70)
    print(title)
    print("=" * 70)


def validate_required_columns(
    df,
    required_columns,
    df_name,
):
    """Validate that required columns exist."""

    missing = [
        column
        for column in required_columns
        if column not in df.columns
    ]

    if missing:
        raise ValueError(
            f"{df_name} is missing required columns: {missing}"
        )

    print(
        f"Required {df_name.lower()} columns: OK"
    )


# ============================================================
# MAIN
# ============================================================

def main():

    print("=" * 70)
    print(
        "NORTHSTAR MODEL VALIDATION — "
        "CALIBRATION ANALYSIS V0.2"
    )
    print("=" * 70)

    # --------------------------------------------------------
    # 1. LOAD BASELINE PREDICTIONS
    # --------------------------------------------------------

    print_section("[1] LOADING BASELINE PREDICTIONS")

    if not PREDICTIONS_PATH.exists():
        raise FileNotFoundError(
            f"Baseline predictions not found:\n"
            f"{PREDICTIONS_PATH}"
        )

    predictions = pd.read_csv(
        PREDICTIONS_PATH
    )

    print(
        f"Predictions shape:   {predictions.shape}"
    )

    # --------------------------------------------------------
    # 2. BASIC VALIDATION CHECKS
    # --------------------------------------------------------

    print_section("[2] BASIC VALIDATION CHECKS")

    required_columns = [
        ID_COLUMN,
        TARGET_COLUMN,
        PROBABILITY_COLUMN,
        PREDICTION_COLUMN,
    ]

    validate_required_columns(
        predictions,
        required_columns,
        "prediction",
    )

    ids_unique = predictions[
        ID_COLUMN
    ].is_unique

    print(
        f"Prediction IDs unique: {ids_unique}"
    )

    if not ids_unique:
        raise ValueError(
            "Prediction IDs are not unique."
        )

    # --------------------------------------------------------
    # 3. TARGET VALIDATION
    # --------------------------------------------------------

    print_section("[3] TARGET VALIDATION")

    missing_target = predictions[
        TARGET_COLUMN
    ].isna().sum()

    print(
        f"Missing target values:   {missing_target}"
    )

    if missing_target > 0:
        raise ValueError(
            "Missing target values detected."
        )

    target_values = set(
        predictions[TARGET_COLUMN].unique()
    )

    print(
        f"Target values:             "
        f"{sorted(target_values)}"
    )

    if not target_values.issubset({0, 1}):
        raise ValueError(
            "Target must contain only 0 and 1."
        )

    # --------------------------------------------------------
    # 4. PROBABILITY VALIDATION
    # --------------------------------------------------------

    print_section("[4] PROBABILITY VALIDATION")

    missing_probability = predictions[
        PROBABILITY_COLUMN
    ].isna().sum()

    print(
        f"Missing probabilities:    "
        f"{missing_probability}"
    )

    if missing_probability > 0:
        raise ValueError(
            "Missing predicted probabilities detected."
        )

    probability = predictions[
        PROBABILITY_COLUMN
    ].astype(float)

    probability_min = probability.min()
    probability_max = probability.max()

    n_unique_probability = (
        probability.nunique()
    )

    print(
        f"Probability minimum:      "
        f"{probability_min:.10f}"
    )

    print(
        f"Probability maximum:      "
        f"{probability_max:.10f}"
    )

    print(
        f"Unique probability values:{n_unique_probability:,}"
    )

    if (
        probability_min < 0
        or probability_max > 1
    ):
        raise ValueError(
            "Predicted probabilities must be in [0, 1]."
        )

    # A binary 0/1 prediction is not suitable for
    # probability calibration analysis.
    if n_unique_probability <= 2:

        raise ValueError(
            "\n"
            "The probability column appears to contain "
            "hard class predictions rather than continuous "
            "predicted probabilities.\n"
            f"Column: {PROBABILITY_COLUMN}\n"
            f"Unique values: {n_unique_probability}"
        )

    print(
        "Continuous probability check: OK"
    )

    # --------------------------------------------------------
    # 5. PREDICTION CONSISTENCY CHECK
    # --------------------------------------------------------

    print_section("[5] PREDICTION CONSISTENCY CHECK")

    expected_prediction = (
        probability >= 0.50
    ).astype(int)

    stored_prediction = (
        predictions[
            PREDICTION_COLUMN
        ].astype(int)
    )

    prediction_consistent = (
        expected_prediction
        == stored_prediction
    ).all()

    print(
        f"Stored predictions consistent "
        f"with 0.50 threshold: {prediction_consistent}"
    )

    if not prediction_consistent:

        inconsistent_count = (
            expected_prediction
            != stored_prediction
        ).sum()

        print(
            f"Inconsistent predictions: "
            f"{inconsistent_count:,}"
        )

        print(
            "WARNING: stored y_prediction does not "
            "match y_probability >= 0.50."
        )

    # --------------------------------------------------------
    # 6. BASIC DATASET STATISTICS
    # --------------------------------------------------------

    print_section("[6] BASIC DATASET STATISTICS")

    y_true = (
        predictions[TARGET_COLUMN]
        .astype(int)
    )

    y_probability = probability

    n_observations = len(predictions)

    observed_bad_rate = (
        y_true.mean()
    )

    mean_predicted_probability = (
        y_probability.mean()
    )

    print(
        f"Observations:              "
        f"{n_observations:,}"
    )

    print(
        f"Observed bad rate:         "
        f"{observed_bad_rate:.6f}"
    )

    print(
        f"Mean predicted probability:"
        f"{mean_predicted_probability:.6f}"
    )

    # --------------------------------------------------------
    # 7. OVERALL CALIBRATION METRICS
    # --------------------------------------------------------

    print_section("[7] OVERALL CALIBRATION METRICS")

    #
    # Calibration-in-the-large
    #
    # Positive:
    #     average predicted risk is higher than
    #     observed event rate.
    #
    # Negative:
    #     average predicted risk is lower than
    #     observed event rate.
    #

    calibration_in_the_large = (
        mean_predicted_probability
        - observed_bad_rate
    )

    brier_score = brier_score_loss(
        y_true,
        y_probability,
    )

    logloss = log_loss(
        y_true,
        y_probability,
    )

    print(
        f"Calibration-in-the-large: "
        f"{calibration_in_the_large:+.6f}"
    )

    print(
        f"Brier score:              "
        f"{brier_score:.6f}"
    )

    print(
        f"Log loss:                  "
        f"{logloss:.6f}"
    )

    # --------------------------------------------------------
    # 8. CALIBRATION BY DECILE
    # --------------------------------------------------------

    print_section("[8] CALIBRATION BY DECILE")

    calibration_data = predictions[
        [
            ID_COLUMN,
            TARGET_COLUMN,
            PROBABILITY_COLUMN,
        ]
    ].copy()

    #
    # Rank first.
    #
    # This makes qcut robust when multiple observations
    # have exactly the same predicted probability.
    #

    calibration_data["_probability_rank"] = (
        calibration_data[
            PROBABILITY_COLUMN
        ].rank(
            method="first"
        )
    )

    calibration_data["risk_decile"] = (
        pd.qcut(
            calibration_data[
                "_probability_rank"
            ],
            q=N_BINS,
            labels=False,
        )
        + 1
    )

    decile_rows = []

    for decile in range(
        1,
        N_BINS + 1,
    ):

        group = calibration_data[
            calibration_data["risk_decile"]
            == decile
        ]

        n = len(group)

        mean_predicted = (
            group[
                PROBABILITY_COLUMN
            ].mean()
        )

        observed_rate = (
            group[
                TARGET_COLUMN
            ].mean()
        )

        calibration_error = (
            observed_rate
            - mean_predicted
        )

        absolute_error = abs(
            calibration_error
        )

        decile_rows.append(
            {
                "risk_decile": decile,

                "n_observations": n,

                "mean_predicted_probability":
                    mean_predicted,

                "observed_bad_rate":
                    observed_rate,

                "calibration_error":
                    calibration_error,

                "absolute_calibration_error":
                    absolute_error,

                "min_predicted_probability":
                    group[
                        PROBABILITY_COLUMN
                    ].min(),

                "max_predicted_probability":
                    group[
                        PROBABILITY_COLUMN
                    ].max(),

                "bad_count":
                    int(
                        group[
                            TARGET_COLUMN
                        ].sum()
                    ),
            }
        )

    calibration_by_decile = (
        pd.DataFrame(
            decile_rows
        )
    )

    print(
        calibration_by_decile.to_string(
            index=False,
            float_format=lambda x:
                f"{x:.6f}",
        )
    )

    # --------------------------------------------------------
    # 9. AGGREGATE CALIBRATION ERRORS
    # --------------------------------------------------------

    print_section("[9] AGGREGATE CALIBRATION ERRORS")

    mae_calibration_error = (
        calibration_by_decile[
            "absolute_calibration_error"
        ].mean()
    )

    max_calibration_error = (
        calibration_by_decile[
            "absolute_calibration_error"
        ].max()
    )

    weighted_calibration_error = (
        np.average(
            calibration_by_decile[
                "absolute_calibration_error"
            ],
            weights=calibration_by_decile[
                "n_observations"
            ],
        )
    )

    print(
        f"Mean absolute calibration error: "
        f"{mae_calibration_error:.6f}"
    )

    print(
        f"Maximum absolute calibration error: "
        f"{max_calibration_error:.6f}"
    )

    print(
        f"Weighted calibration error: "
        f"{weighted_calibration_error:.6f}"
    )

    # --------------------------------------------------------
    # 10. SAVE CALIBRATION METRICS
    # --------------------------------------------------------

    print_section("[10] SAVING CALIBRATION METRICS")

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    metrics = pd.DataFrame(
        [
            {
                "metric":
                    "n_observations",

                "value":
                    n_observations,
            },
            {
                "metric":
                    "observed_bad_rate",

                "value":
                    observed_bad_rate,
            },
            {
                "metric":
                    "mean_predicted_probability",

                "value":
                    mean_predicted_probability,
            },
            {
                "metric":
                    "calibration_in_the_large",

                "value":
                    calibration_in_the_large,
            },
            {
                "metric":
                    "brier_score",

                "value":
                    brier_score,
            },
            {
                "metric":
                    "log_loss",

                "value":
                    logloss,
            },
            {
                "metric":
                    "mean_absolute_calibration_error",

                "value":
                    mae_calibration_error,
            },
            {
                "metric":
                    "maximum_absolute_calibration_error",

                "value":
                    max_calibration_error,
            },
            {
                "metric":
                    "weighted_calibration_error",

                "value":
                    weighted_calibration_error,
            },
        ]
    )

    metrics.to_csv(
        METRICS_PATH,
        index=False,
    )

    calibration_by_decile.to_csv(
        DECILE_PATH,
        index=False,
    )

    print(
        f"Metrics saved:            "
        f"{METRICS_PATH}"
    )

    print(
        f"Decile table saved:       "
        f"{DECILE_PATH}"
    )

    # --------------------------------------------------------
    # 11. CALIBRATION CURVE
    # --------------------------------------------------------

    print_section("[11] CALIBRATION CURVE")

    x = calibration_by_decile[
        "mean_predicted_probability"
    ]

    y = calibration_by_decile[
        "observed_bad_rate"
    ]

    plt.figure(
        figsize=(8, 8)
    )

    #
    # Perfect calibration reference.
    #

    plt.plot(
        [0, 1],
        [0, 1],
        linestyle="--",
        label="Perfect calibration",
    )

    #
    # Model calibration.
    #

    plt.plot(
        x,
        y,
        marker="o",
        label="Model calibration",
    )

    plt.xlabel(
        "Mean predicted probability"
    )

    plt.ylabel(
        "Observed bad rate"
    )

    plt.title(
        "Calibration Curve — Validation Sample"
    )

    plt.legend()

    plt.grid(
        True,
        alpha=0.3,
    )

    plt.tight_layout()

    plt.savefig(
        PLOT_PATH,
        dpi=150,
    )

    plt.close()

    print(
        f"Calibration curve saved: "
        f"{PLOT_PATH}"
    )

    # --------------------------------------------------------
    # 12. VALIDATION SUMMARY
    # --------------------------------------------------------

    print_section("[12] VALIDATION SUMMARY")

    print(
        f"Overall observed bad rate: "
        f"{observed_bad_rate:.4f}"
    )

    print(
        f"Mean predicted probability: "
        f"{mean_predicted_probability:.4f}"
    )

    print(
        f"Calibration-in-the-large: "
        f"{calibration_in_the_large:+.4f}"
    )

    print(
        f"Mean absolute calibration error: "
        f"{mae_calibration_error:.4f}"
    )

    print(
        f"Maximum absolute calibration error: "
        f"{max_calibration_error:.4f}"
    )

    print(
        f"Brier score: "
        f"{brier_score:.4f}"
    )

    print(
        f"Log loss: "
        f"{logloss:.4f}"
    )

    print()
    print("=" * 70)
    print(
        "CALIBRATION ANALYSIS COMPLETED"
    )
    print("=" * 70)


if __name__ == "__main__":
    main()